services:

  database:
    image: mongo:latest
    container_name: voyager_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: voyager_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://database:27017/smart-voyager
      - JWT_SECRET
      - GROQ_API_KEY
    depends_on:
      - database

  web:
    build: ./web
    container_name: voyager_web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: voyager_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

volumes:
  mongo_data: